import { EquipmentModel } from './equipments';

export interface GearModel extends EquipmentModel {
  readonly type: 'gear';
}

export const gears = {
  acid: {
    uniqueIdentifier: 'acid',
    type: 'gear',
    name: 'Ácido',
    description: '',
  },
  alchemistsFire: {
    uniqueIdentifier: 'alchemistsFire',
    type: 'gear',
    name: 'Fogo alquímico',
    description: '',
  },
  ammunition: {
    uniqueIdentifier: 'ammunition',
    type: 'gear',
    name: 'Munição',
    description: '',
  },
  antitoxin: {
    uniqueIdentifier: 'antitoxin',
    type: 'gear',
    name: 'Antitoxina',
    description: '',
  },
  arcaneFocus: {
    uniqueIdentifier: 'arcaneFocus',
    type: 'gear',
    name: 'Foco arcano',
    description: '',
  },
  backpack: {
    uniqueIdentifier: 'backpack',
    type: 'gear',
    name: 'Mochila',
    description: '',
  },
  ballBearings: {
    uniqueIdentifier: 'ballBearings',
    type: 'gear',
    name: 'Esferas de metal',
    description: '',
  },
  barrel: {
    uniqueIdentifier: 'barrel',
    type: 'gear',
    name: 'Barril',
    description: '',
  },
  basket: {
    uniqueIdentifier: 'basket',
    type: 'gear',
    name: 'Cesta',
    description: '',
  },
  bedroll: {
    uniqueIdentifier: 'bedroll',
    type: 'gear',
    name: 'Saco de dormir',
    description: '',
  },
  bell: {
    uniqueIdentifier: 'bell',
    type: 'gear',
    name: 'Sino',
    description: '',
  },
  blanket: {
    uniqueIdentifier: 'blanket',
    type: 'gear',
    name: 'Cobertor',
    description: '',
  },
  blockAndTackle: {
    uniqueIdentifier: 'blockAndTackle',
    type: 'gear',
    name: 'Roldana e polias',
    description: '',
  },
  book: {
    uniqueIdentifier: 'book',
    type: 'gear',
    name: 'Livro',
    description: '',
  },
  glassBottle: {
    uniqueIdentifier: 'glassBottle',
    type: 'gear',
    name: 'Garrafa, vidro',
    description: '',
  },
  bucket: {
    uniqueIdentifier: 'bucket',
    type: 'gear',
    name: 'Balde',
    description: '',
  },
  burglarsPack: {
    uniqueIdentifier: 'burglarsPack',
    type: 'gear',
    name: 'Kit de assaltante',
    description: '',
  },
  caltrops: {
    uniqueIdentifier: 'caltrops',
    type: 'gear',
    name: 'Estrepes',
    description: '',
  },
  candle: {
    uniqueIdentifier: 'candle',
    type: 'gear',
    name: 'Vela',
    description: '',
  },
  crossbowBoltCase: {
    uniqueIdentifier: 'crossbowBoltCase',
    type: 'gear',
    name: 'Estojo, virotes de besta',
    description: '',
  },
  mapOrScrollCase: {
    uniqueIdentifier: 'mapOrScrollCase',
    type: 'gear',
    name: 'Estojo, mapa ou pergaminho',
    description: '',
  },
  chain: {
    uniqueIdentifier: 'chain',
    type: 'gear',
    name: 'Corrente',
    description: '',
  },
  chest: {
    uniqueIdentifier: 'chest',
    type: 'gear',
    name: 'Baú',
    description: '',
  },
  climbersKit: {
    uniqueIdentifier: 'climbersKit',
    type: 'gear',
    name: 'Kit de alpinista',
    description: '',
  },
  fineClothes: {
    uniqueIdentifier: 'fineClothes',
    type: 'gear',
    name: 'Roupas, finas',
    description: '',
  },
  travelersClothes: {
    uniqueIdentifier: 'travelersClothes',
    type: 'gear',
    name: 'Traje, viajante',
    description: '',
  },
  componentPouch: {
    uniqueIdentifier: 'componentPouch',
    type: 'gear',
    name: 'Bolsa para componentes',
    description: '',
  },
  costume: {
    uniqueIdentifier: 'costume',
    type: 'gear',
    name: 'Fantasia',
    description: '',
  },
  crowbar: {
    uniqueIdentifier: 'crowbar',
    type: 'gear',
    name: 'Pé de cabra',
    description: '',
  },
  diplomatsPack: {
    uniqueIdentifier: 'diplomatsPack',
    type: 'gear',
    name: 'Kit de diplomata',
    description: '',
  },
  druidicFocus: {
    uniqueIdentifier: 'druidicFocus',
    type: 'gear',
    name: 'Foco druídico',
    description: '',
  },
  dungeoneersPack: {
    uniqueIdentifier: 'dungeoneersPack',
    type: 'gear',
    name: 'Kit de aventureiro',
    description: '',
  },
  entertainersPack: {
    uniqueIdentifier: 'entertainersPack',
    type: 'gear',
    name: 'Kit de artista',
    description: '',
  },
  explorersPack: {
    uniqueIdentifier: 'explorersPack',
    type: 'gear',
    name: 'Kit de explorador',
    description: '',
  },
  flask: {
    uniqueIdentifier: 'flask',
    type: 'gear',
    name: 'Frasco',
    description: '',
  },
  grapplingHook: {
    uniqueIdentifier: 'grapplingHook',
    type: 'gear',
    name: 'Arpéu',
    description: '',
  },
  healersKit: {
    uniqueIdentifier: 'healersKit',
    type: 'gear',
    name: 'Kit de curandeiro',
    description: '',
  },
  holySymbol: {
    uniqueIdentifier: 'holySymbol',
    type: 'gear',
    name: 'Símbolo sagrado',
    description: '',
  },
  holyWater: {
    uniqueIdentifier: 'holyWater',
    type: 'gear',
    name: 'Água benta',
    description: '',
  },
  huntingTrap: {
    uniqueIdentifier: 'huntingTrap',
    type: 'gear',
    name: 'Armadilha de caça',
    description: '',
  },
  ink: {
    uniqueIdentifier: 'ink',
    type: 'gear',
    name: 'Tinta',
    description: '',
  },
  inkPen: {
    uniqueIdentifier: 'inkPen',
    type: 'gear',
    name: 'Caneta tinteiro',
    description: '',
  },
  jug: {
    uniqueIdentifier: 'jug',
    type: 'gear',
    name: 'Jarro',
    description: '',
  },
  ladder: {
    uniqueIdentifier: 'ladder',
    type: 'gear',
    name: 'Escada',
    description: '',
  },
  lamp: {
    uniqueIdentifier: 'lamp',
    type: 'gear',
    name: 'Lamparina',
    description: '',
  },
  bullseyeLantern: {
    uniqueIdentifier: 'bullseyeLantern',
    type: 'gear',
    name: 'Lanterna de foco',
    description: '',
  },
  hoodedLantern: {
    uniqueIdentifier: 'hoodedLantern',
    type: 'gear',
    name: 'Lanterna coberta',
    description: '',
  },
  lock: {
    uniqueIdentifier: 'lock',
    type: 'gear',
    name: 'Cadeado',
    description: '',
  },
  magnifyingGlass: {
    uniqueIdentifier: 'magnifyingGlass',
    type: 'gear',
    name: 'Lupa',
    description: '',
  },
  manacles: {
    uniqueIdentifier: 'manacles',
    type: 'gear',
    name: 'Algemas',
    description: '',
  },
  map: {
    uniqueIdentifier: 'map',
    type: 'gear',
    name: 'Mapa',
    description: '',
  },
  mirror: {
    uniqueIdentifier: 'mirror',
    type: 'gear',
    name: 'Espelho',
    description: '',
  },
  net: {
    uniqueIdentifier: 'net',
    type: 'gear',
    name: 'Rede',
    description: '',
  },
  oil: {
    uniqueIdentifier: 'oil',
    type: 'gear',
    name: 'Óleo',
    description: '',
  },
  paper: {
    uniqueIdentifier: 'paper',
    type: 'gear',
    name: 'Papel',
    description: '',
  },
  parchment: {
    uniqueIdentifier: 'parchment',
    type: 'gear',
    name: 'Pergaminho',
    description: '',
  },
  perfume: {
    uniqueIdentifier: 'perfume',
    type: 'gear',
    name: 'Perfume',
    description: '',
  },
  basicPoison: {
    uniqueIdentifier: 'basicPoison',
    type: 'gear',
    name: 'Veneno, básico',
    description: '',
  },
  pole: {
    uniqueIdentifier: 'pole',
    type: 'gear',
    name: 'Haste',
    description: '',
  },
  ironPot: {
    uniqueIdentifier: 'ironPot',
    type: 'gear',
    name: 'Panela, ferro',
    description: '',
  },
  potionOfHealing: {
    uniqueIdentifier: 'potionOfHealing',
    type: 'gear',
    name: 'Poção de cura',
    description: '',
  },
  pouch: {
    uniqueIdentifier: 'pouch',
    type: 'gear',
    name: 'Algibeira',
    description: '',
  },
  priestsPack: {
    uniqueIdentifier: 'priestsPack',
    type: 'gear',
    name: 'Kit de Sacerdote',
    description: '',
  },
  quiver: {
    uniqueIdentifier: 'quiver',
    type: 'gear',
    name: 'Aljava',
    description: '',
  },
  portableRam: {
    uniqueIdentifier: 'portableRam',
    type: 'gear',
    name: 'Aríete, portátil',
    description: '',
  },
  rations: {
    uniqueIdentifier: 'rations',
    type: 'gear',
    name: 'Rações',
    description: '',
  },
  robe: {
    uniqueIdentifier: 'robe',
    type: 'gear',
    name: 'Túnica',
    description: '',
  },
  rope: {
    uniqueIdentifier: 'rope',
    type: 'gear',
    name: 'Corda',
    description: '',
  },
  sack: {
    uniqueIdentifier: 'sack',
    type: 'gear',
    name: 'Saca',
    description: '',
  },
  scholarsPack: {
    uniqueIdentifier: 'scholarsPack',
    type: 'gear',
    name: 'Kit de Erudito',
    description: '',
  },
  shovel: {
    uniqueIdentifier: 'shovel',
    type: 'gear',
    name: 'Pá',
    description: '',
  },
  signalWhistle: {
    uniqueIdentifier: 'signalWhistle',
    type: 'gear',
    name: 'Apito sinalizador',
    description: '',
  },
  spellScrollCantrip: {
    uniqueIdentifier: 'spellScrollCantrip',
    type: 'gear',
    name: 'Pergaminho de magia (truque)',
    description: '',
  },
  spellScrollLevel1: {
    uniqueIdentifier: 'spellScrollLevel1',
    type: 'gear',
    name: 'Pergaminho de magia (1º círculo)',
    description: '',
  },
  ironSpikes: {
    uniqueIdentifier: 'ironSpikes',
    type: 'gear',
    name: 'Estacas, ferro',
    description: '',
  },
  spyglass: {
    uniqueIdentifier: 'spyglass',
    type: 'gear',
    name: 'Luneta',
    description: '',
  },
  string: {
    uniqueIdentifier: 'string',
    type: 'gear',
    name: 'Fio',
    description: '',
  },
  tent: {
    uniqueIdentifier: 'tent',
    type: 'gear',
    name: 'Tenda',
    description: '',
  },
  tinderbox: {
    uniqueIdentifier: 'tinderbox',
    type: 'gear',
    name: 'Caixa para Fogo',
    description: '',
  },
  torch: {
    uniqueIdentifier: 'torch',
    type: 'gear',
    name: 'Tocha',
    description: '',
  },
  vial: {
    uniqueIdentifier: 'vial',
    type: 'gear',
    name: 'Frasco',
    description: '',
  },
  waterskin: {
    uniqueIdentifier: 'waterskin',
    type: 'gear',
    name: 'Cantil',
    description: '',
  },
} as const satisfies Record<string, GearModel>;
