import { DamageTypeModel, damageTypes } from './damage-types';
import { DiceRollModel, dices } from './dices';
import { EquipmentModel } from './equipments';
import {
  weaponMasteryProperties,
  WeaponMasteryPropertyModel,
} from './weapon-mastery-properties';
import { weaponProperties, WeaponPropertyModel } from './weapon-properties';

export interface WeaponModel extends EquipmentModel {
  readonly type: 'weapon';
  readonly weaponType:
    | 'simpleMelee'
    | 'simpleRanged'
    | 'martialMelee'
    | 'martialRanged';
  readonly damageDiceRoll: DiceRollModel;
  readonly damageType: DamageTypeModel;
  readonly properties: WeaponPropertyModel[];
  readonly masteryProperty: WeaponMasteryPropertyModel;
}

// Página do jogador: 215
export const weapons = {
  club: {
    uniqueIdentifier: 'club',
    name: 'Clava',
    type: 'weapon',
    description: '',
    weaponType: 'simpleMelee',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d4,
    },
    damageType: damageTypes.bludgeoning,
    properties: [weaponProperties.light],
    masteryProperty: weaponMasteryProperties.slow,
  },
  dagger: {
    uniqueIdentifier: 'dagger',
    name: 'Adaga',
    type: 'weapon',
    description: '',
    weaponType: 'simpleMelee',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d4,
    },
    damageType: damageTypes.piercing,
    properties: [
      weaponProperties.finesse,
      weaponProperties.light,
      weaponProperties.thrown,
    ],
    masteryProperty: weaponMasteryProperties.nick,
  },
  greatclub: {
    uniqueIdentifier: 'greatclub',
    name: 'Clava grande',
    type: 'weapon',
    description: '',
    weaponType: 'simpleMelee',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d8,
    },
    damageType: damageTypes.bludgeoning,
    properties: [weaponProperties.twoHanded],
    masteryProperty: weaponMasteryProperties.push,
  },
  handaxe: {
    uniqueIdentifier: 'handaxe',
    name: 'Machadinha',
    type: 'weapon',
    description: '',
    weaponType: 'simpleMelee',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d6,
    },
    damageType: damageTypes.slashing,
    properties: [weaponProperties.light, weaponProperties.thrown],
    masteryProperty: weaponMasteryProperties.vex,
  },
  javelin: {
    uniqueIdentifier: 'javelin',
    name: 'Azagaia',
    type: 'weapon',
    description: '',
    weaponType: 'simpleMelee',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d6,
    },
    damageType: damageTypes.piercing,
    properties: [weaponProperties.thrown],
    masteryProperty: weaponMasteryProperties.slow,
  },
  lightHammer: {
    uniqueIdentifier: 'lightHammer',
    name: 'Martelo leve',
    type: 'weapon',
    description: '',
    weaponType: 'simpleMelee',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d4,
    },
    damageType: damageTypes.bludgeoning,
    properties: [weaponProperties.light, weaponProperties.thrown],
    masteryProperty: weaponMasteryProperties.nick,
  },
  mace: {
    uniqueIdentifier: 'mace',
    name: 'Maça',
    type: 'weapon',
    description: '',
    weaponType: 'simpleMelee',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d6,
    },
    damageType: damageTypes.bludgeoning,
    properties: [],
    masteryProperty: weaponMasteryProperties.sap,
  },
  quarterstaff: {
    uniqueIdentifier: 'quarterstaff',
    name: 'Bastão',
    type: 'weapon',
    description: '',
    weaponType: 'simpleMelee',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d6,
    },
    damageType: damageTypes.bludgeoning,
    properties: [weaponProperties.versatile],
    masteryProperty: weaponMasteryProperties.topple,
  },
  sickle: {
    uniqueIdentifier: 'sickle',
    name: 'Foice',
    type: 'weapon',
    description: '',
    weaponType: 'simpleMelee',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d4,
    },
    damageType: damageTypes.slashing,
    properties: [weaponProperties.light],
    masteryProperty: weaponMasteryProperties.nick,
  },
  spear: {
    uniqueIdentifier: 'spear',
    name: 'Lança',
    type: 'weapon',
    description: '',
    weaponType: 'simpleMelee',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d6,
    },
    damageType: damageTypes.piercing,
    properties: [weaponProperties.thrown, weaponProperties.versatile],
    masteryProperty: weaponMasteryProperties.sap,
  },

  dart: {
    uniqueIdentifier: 'dart',
    name: 'Dardo',
    type: 'weapon',
    description: '',
    weaponType: 'simpleRanged',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d4,
    },
    damageType: damageTypes.piercing,
    properties: [weaponProperties.finesse, weaponProperties.thrown],
    masteryProperty: weaponMasteryProperties.vex,
  },
  lightCrossbow: {
    uniqueIdentifier: 'lightCrossbow',
    name: 'Besta leve',
    type: 'weapon',
    description: '',
    weaponType: 'simpleRanged',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d8,
    },
    damageType: damageTypes.piercing,
    properties: [
      weaponProperties.ammunition,
      weaponProperties.loading,
      weaponProperties.twoHanded,
    ],
    masteryProperty: weaponMasteryProperties.slow,
  },
  shortbow: {
    uniqueIdentifier: 'shortbow',
    name: 'Arco curto',
    type: 'weapon',
    description: '',
    weaponType: 'simpleRanged',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d6,
    },
    damageType: damageTypes.piercing,
    properties: [weaponProperties.ammunition, weaponProperties.twoHanded],
    masteryProperty: weaponMasteryProperties.vex,
  },
  sling: {
    uniqueIdentifier: 'sling',
    name: 'Funda',
    type: 'weapon',
    description: '',
    weaponType: 'simpleRanged',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d4,
    },
    damageType: damageTypes.bludgeoning,
    properties: [weaponProperties.ammunition],
    masteryProperty: weaponMasteryProperties.slow,
  },

  battleaxe: {
    uniqueIdentifier: 'battleaxe',
    name: 'Machado de batalha',
    type: 'weapon',
    description: '',
    weaponType: 'martialMelee',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d8,
    },
    damageType: damageTypes.slashing,
    properties: [weaponProperties.versatile],
    masteryProperty: weaponMasteryProperties.topple,
  },
  flail: {
    uniqueIdentifier: 'flail',
    name: 'Mangual',
    type: 'weapon',
    description: '',
    weaponType: 'martialMelee',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d8,
    },
    damageType: damageTypes.bludgeoning,
    properties: [],
    masteryProperty: weaponMasteryProperties.sap,
  },
  glaive: {
    uniqueIdentifier: 'glaive',
    name: 'Glaive',
    type: 'weapon',
    description: '',
    weaponType: 'martialMelee',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d10,
    },
    damageType: damageTypes.slashing,
    properties: [
      weaponProperties.heavy,
      weaponProperties.reach,
      weaponProperties.twoHanded,
    ],
    masteryProperty: weaponMasteryProperties.graze,
  },
  greataxe: {
    uniqueIdentifier: 'greataxe',
    name: 'Machado grande',
    type: 'weapon',
    description: '',
    weaponType: 'martialMelee',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d12,
    },
    damageType: damageTypes.slashing,
    properties: [weaponProperties.heavy, weaponProperties.twoHanded],
    masteryProperty: weaponMasteryProperties.cleave,
  },
  greatsword: {
    uniqueIdentifier: 'greatsword',
    name: 'Espada grande',
    type: 'weapon',
    description: '',
    weaponType: 'martialMelee',
    damageDiceRoll: {
      quantity: 2,
      dice: dices.d6,
    },
    damageType: damageTypes.slashing,
    properties: [weaponProperties.heavy, weaponProperties.twoHanded],
    masteryProperty: weaponMasteryProperties.graze,
  },
  halberd: {
    uniqueIdentifier: 'halberd',
    name: 'Alabarda',
    type: 'weapon',
    description: '',
    weaponType: 'martialMelee',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d10,
    },
    damageType: damageTypes.slashing,
    properties: [
      weaponProperties.heavy,
      weaponProperties.reach,
      weaponProperties.twoHanded,
    ],
    masteryProperty: weaponMasteryProperties.cleave,
  },
  lance: {
    uniqueIdentifier: 'lance',
    name: 'Lança',
    type: 'weapon',
    description: '',
    weaponType: 'martialMelee',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d10,
    },
    damageType: damageTypes.piercing,
    properties: [
      weaponProperties.heavy,
      weaponProperties.reach,
      weaponProperties.twoHanded,
    ],
    masteryProperty: weaponMasteryProperties.topple,
  },
  longsword: {
    uniqueIdentifier: 'longsword',
    name: 'Espada longa',
    type: 'weapon',
    description: '',
    weaponType: 'martialMelee',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d8,
    },
    damageType: damageTypes.slashing,
    properties: [weaponProperties.versatile],
    masteryProperty: weaponMasteryProperties.sap,
  },
  maul: {
    uniqueIdentifier: 'maul',
    name: 'Malho',
    type: 'weapon',
    description: '',
    weaponType: 'martialMelee',
    damageDiceRoll: {
      quantity: 2,
      dice: dices.d6,
    },
    damageType: damageTypes.bludgeoning,
    properties: [weaponProperties.heavy, weaponProperties.twoHanded],
    masteryProperty: weaponMasteryProperties.topple,
  },
  morningstar: {
    uniqueIdentifier: 'morningstar',
    name: 'Maça estela',
    type: 'weapon',
    description: '',
    weaponType: 'martialMelee',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d8,
    },
    damageType: damageTypes.piercing,
    properties: [],
    masteryProperty: weaponMasteryProperties.sap,
  },
  pike: {
    uniqueIdentifier: 'pike',
    name: 'Lança longa',
    type: 'weapon',
    description: '',
    weaponType: 'martialMelee',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d10,
    },
    damageType: damageTypes.piercing,
    properties: [
      weaponProperties.heavy,
      weaponProperties.reach,
      weaponProperties.twoHanded,
    ],
    masteryProperty: weaponMasteryProperties.push,
  },
  rapier: {
    uniqueIdentifier: 'rapier',
    name: 'Rapieira',
    type: 'weapon',
    description: '',
    weaponType: 'martialMelee',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d8,
    },
    damageType: damageTypes.piercing,
    properties: [weaponProperties.finesse],
    masteryProperty: weaponMasteryProperties.vex,
  },
  scimitar: {
    uniqueIdentifier: 'scimitar',
    name: 'Cimitarra',
    type: 'weapon',
    description: '',
    weaponType: 'martialMelee',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d6,
    },
    damageType: damageTypes.slashing,
    properties: [weaponProperties.finesse, weaponProperties.light],
    masteryProperty: weaponMasteryProperties.nick,
  },
  shortsword: {
    uniqueIdentifier: 'shortsword',
    name: 'Espada curta',
    type: 'weapon',
    description: '',
    weaponType: 'martialMelee',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d6,
    },
    damageType: damageTypes.piercing,
    properties: [weaponProperties.finesse, weaponProperties.light],
    masteryProperty: weaponMasteryProperties.vex,
  },
  trident: {
    uniqueIdentifier: 'trident',
    name: 'Tridente',
    type: 'weapon',
    description: '',
    weaponType: 'martialMelee',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d8,
    },
    damageType: damageTypes.piercing,
    properties: [weaponProperties.thrown, weaponProperties.versatile],
    masteryProperty: weaponMasteryProperties.topple,
  },
  warhammer: {
    uniqueIdentifier: 'warhammer',
    name: 'Martelo de guerra',
    type: 'weapon',
    description: '',
    weaponType: 'martialMelee',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d8,
    },
    damageType: damageTypes.bludgeoning,
    properties: [weaponProperties.versatile],
    masteryProperty: weaponMasteryProperties.push,
  },
  warPick: {
    uniqueIdentifier: 'warPick',
    name: 'Picareta de guerra',
    type: 'weapon',
    description: '',
    weaponType: 'martialMelee',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d8,
    },
    damageType: damageTypes.piercing,
    properties: [weaponProperties.versatile],
    masteryProperty: weaponMasteryProperties.sap,
  },
  whip: {
    uniqueIdentifier: 'whip',
    name: 'Chicote',
    type: 'weapon',
    description: '',
    weaponType: 'martialMelee',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d4,
    },
    damageType: damageTypes.slashing,
    properties: [weaponProperties.finesse, weaponProperties.reach],
    masteryProperty: weaponMasteryProperties.slow,
  },

  blowgun: {
    uniqueIdentifier: 'blowgun',
    name: 'Zarabatana',
    type: 'weapon',
    description: '',
    weaponType: 'martialRanged',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d1,
    },
    damageType: damageTypes.piercing,
    properties: [weaponProperties.ammunition, weaponProperties.loading],
    masteryProperty: weaponMasteryProperties.vex,
  },
  handCrossbow: {
    uniqueIdentifier: 'handCrossbow',
    name: 'Besta de mão',
    type: 'weapon',
    description: '',
    weaponType: 'martialRanged',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d6,
    },
    damageType: damageTypes.piercing,
    properties: [
      weaponProperties.ammunition,
      weaponProperties.light,
      weaponProperties.loading,
    ],
    masteryProperty: weaponMasteryProperties.vex,
  },
  heavyCrossbow: {
    uniqueIdentifier: 'heavyCrossbow',
    name: 'Besta pesada',
    type: 'weapon',
    description: '',
    weaponType: 'martialRanged',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d10,
    },
    damageType: damageTypes.piercing,
    properties: [
      weaponProperties.ammunition,
      weaponProperties.heavy,
      weaponProperties.loading,
      weaponProperties.twoHanded,
    ],
    masteryProperty: weaponMasteryProperties.push,
  },
  longbow: {
    uniqueIdentifier: 'longbow',
    name: 'Arco longo',
    type: 'weapon',
    description: '',
    weaponType: 'martialRanged',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d8,
    },
    damageType: damageTypes.piercing,
    properties: [
      weaponProperties.ammunition,
      weaponProperties.heavy,
      weaponProperties.twoHanded,
    ],
    masteryProperty: weaponMasteryProperties.slow,
  },
  musket: {
    uniqueIdentifier: 'musket',
    name: 'Mosquete',
    type: 'weapon',
    description: '',
    weaponType: 'martialRanged',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d12,
    },
    damageType: damageTypes.piercing,
    properties: [
      weaponProperties.ammunition,
      weaponProperties.loading,
      weaponProperties.twoHanded,
    ],
    masteryProperty: weaponMasteryProperties.slow,
  },
  pistol: {
    uniqueIdentifier: 'pistol',
    name: 'Pistola',
    type: 'weapon',
    description: '',
    weaponType: 'martialRanged',
    damageDiceRoll: {
      quantity: 1,
      dice: dices.d10,
    },
    damageType: damageTypes.piercing,
    properties: [weaponProperties.ammunition, weaponProperties.loading],
    masteryProperty: weaponMasteryProperties.vex,
  },
} as const satisfies Record<string, WeaponModel>;
